### ISSUE TITLE
Magic string mismatch

### ISSUE THREAD

**Issue by ad-on-is** [iliasChymas/ApexCacheUpdater#1]
It used to run fine, but now I'm getting the following error.

```
Merging files r5apex.dxvk-cache output.dxvk-cache
Error: Error { kind: InvalidData, message: "Magic string mismatch" }
```

**Comment by iliasChymas** [comment]
Welp it seems that the guy who uploaded the cache compressed the file. This is why this script could not merge the files the one was an  zstd compressed file and the other was your current cache. Now i changed it. The script now downloads the .zst file and then it extracts the dxvk_cache. Now it should be working. I will download Apex again to test further but will take some time. Please inform me if your problem is fixed!

**Comment by ad-on-is** [comment]
Thx... seems to work now

```
output.dxvk-cache.zst: 9169944 bytes                                           
Merging files r5apex.dxvk-cache output.dxvk-cache
Detected state cache version v10
Merging r5apex.dxvk-cache (1/2)... 3074 new entries
Merging output.dxvk-cache (2/2)... 37128 new entries
Writing 40202 entries to file output.dxvk-cache
Finished
```
